### PR TITLE
Pull request to get Ari's changes

### PR DESCRIPTION
**Pull request by slarson**
Will be modifying the incoming pull request to get rid of files we don't want @aribrich

### CODE REVIEW

**Comment by pgleeson** [comment]
Is there anything beyond  CompareMain.py that should be actually included from this pr? None of the c302 files should change if they've been generated from the latest code, and the .ideas folder shouldn't be committed.

**Comment by aribrich** [comment]
CompareMain.py is the only file that I am publishing. All the other changes are incidental. I tried adding the .idea folder to a .gitignore directory, but that didn't seem to take. The c302 file changes are junk.

**Comment by slarson** [comment]
Yup -- hold off a bit @pgleeson -- doing a bit more modification on this one.

**Comment by slarson** [comment]
As soon as Ari merges [this](https://github.com/aribrich/CElegansNeuroML/pull/1) we should be good to go.

**Comment by slarson** [comment]
Hmm -- ok it looks like unfortunately my pull request didn't do it even after Ari's merge.  I'm going to try again.

**Comment by slarson** [comment]
@aribrich OK I think the changes on aribrich/CElegansNeuroML just need to be wiped and started from scratch.  Go to the settings (bottom of right hand panel) and delete the repo altogether (last option).  Then fork CElegansNeuroML again.  Then, add your CompareMain.py on top of what is there so that it is actually the only thing that is different.  I think what is messing us up are all the changes in [this commit](https://github.com/aribrich/CElegansNeuroML/commit/2cd25c020c0f0cfbac73d3be77b680dbb60be94f).  So when we can start without that I think it will be much more clean and straightforward.  Once we do that we'll open another pull request (& then we'll be in good shape for future contributions as well)

**Pull request closed without merging**
