### PR TITLE
Separation of generic synapse into neuron-to-neuron and neuron-to-muscle synapses on all levels.

### PR DESCRIPTION
**Pull request by ed5000**

### CODE REVIEW

**Comment by pgleeson** [comment]
@ed5000 @FinnK quick question, why is the phase offset target 90 rather than 180? This is the ideal target behaviour for the muscles (and presumably the D/V motorneurons):

figure_3

**Comment by FinnK** [comment]
It should probably be 180, I think 90 is a mistake.

**Comment by ed5000** [comment]
This has been amended in today's commit. 
Best of luck with the project.
Regards,
Eoghan

**Comment by pgleeson** [comment]
Thanks for this @ed5000

**Pull request merged**
