### PR TITLE
Python scripts tester

### PR DESCRIPTION
**Pull request by brijeshmodi12**
Python script for testing RegenerateConnectome.py, SpreadsheetDataReader.py, OpenWormReader.py via py.test

### CODE REVIEW

**Comment by slarson** [comment]
@brijeshmodi12 Looking good!  Some feedback; can you add the following to the .gitignore ?

>.idea/*

That stuff is considered "IDE-specific" so we try to avoid checking it in.  

If you check it into the same branch as the one that you are doing the pull request from we'll see it automatically update in this thread.

**Comment by brijeshmodi12** [comment]
@slarson  I have made the necessary changes.

**Comment by pgleeson** [comment]
Thanks @brijeshmodi12. Can you also remove the idea related files from this PR?

**Comment by brijeshmodi12** [comment]
@pgleeson Done!

**Comment by pgleeson** [comment]
Thanks @brijeshmodi12. Merged.

**Pull request merged**
