### PR TITLE
adding CompareMain.py

### PR DESCRIPTION
**Pull request by aribrich**
File is written to read to set excel files in their respective directories. It will need to be pointed to those files before use.

### CODE REVIEW

**Comment by slarson** [comment]
@aribrich Woo hoo!  There it is!  OK -- couple things though.  I see you have some hardcoded file paths at the bottom of the file -- could those be made relative paths?

https://stackoverflow.com/questions/918154/relative-paths-in-python

Also, is the main root directory the best place for this file, or is it maybe better under the scripts directory under c302?

Cheers!

**Comment by aribrich** [comment]
@slarson it isn't a problem to make relative paths. I had that in place before, but I wasn't sure if that would be implemented the same way in an online directory. As for where to put it, I don't have a preference. I just put it there because the excel files are currently there. would you prefer it be placed in the c302 directory?

**Comment by aribrich** [comment]
@slarson the changes that you had mentioned have been made. How does it look?

**Comment by pgleeson** [comment]
Thanks for this @aribrich, Could you change the output of this script to give more of a readable summary of the differences? e.g.

**Connections identical: (2344)**
**Connections in CElegansNeuronTables.xls, missing in NeuronConnectFormatted.xlsx (63 total)**
ADAL->ADEL (7, Gap Junction)
....

**Connections in NeuronConnectFormatted.xlsx, missing in CElegansNeuronTables.xls (33 total)**
ADER->ADLR (2, Sp)
...

**Connections with different numbers of synapses**
...


**Connections with different types of synapses**
...

**Comment by aribrich** [comment]
Sorry it took so long. Let me know if you think it needs more changes.

**Comment by aribrich** [comment]
Hi @slarson sorry, I didn't use your handle in the last message. I uploaded a new version of the program. I read through the threads and it may obsolete, but let me know what you think if we can use it. I have been mostly doing some research into the last paper we discussed into prediction of stimulation paths, but maybe we can discuss that later.

**Pull request merged**
